# -*- coding: utf-8 -*-
"""Exercícios7.PY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFpbcv_K95D0sqTD-XycwFDdVSgPlxF0
"""

#EXERCÍCIO 1

contagem = 10

while contagem > 0:
     print('Contagem -',contagem)
     contagem -= 1
     if contagem == 0:
      print('FOGO!')

#EXERCÍCIO 2

num = int(input('Digite um número inteiro positivo para saber a soma de seus pares = '))
soma = sum((range(2,num+1,2)))
print(soma)

#EXERCÍCIO 3

tabu= int(input("Tabuada do numero: "))

for x in range(10):
    print('{} X {} = {}'.format(tabu, x+1, tabu*(x+1)))

#EXERCÍCIO 4

numero = 99
while numero >= 1:
         print(numero)
         numero -= 2